name: gad_2023_early_2
description: A fLutter project that replicates emag.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  freezed_annotation: ^2.2.0
  flutter_redux: ^0.10.0
  json_annotation: ^4.8.1
  cupertino_icons: ^1.0.5
  firebase_auth: ^4.5.0
  firebase_core: ^2.11.0
  redux_epics: ^0.15.1
  rxdart: ^0.27.7
  redux: ^5.0.0

dev_dependencies:
  build_runner: ^2.3.3
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  freezed: ^2.3.3
  json_serializable: ^6.6.2

flutter:
  uses-material-design: true
