// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show TargetPlatform, defaultTargetPlatform, kIsWeb;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      // ignore: no_default_cases
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA4NB9-L396LvxrAuiE8N1_WGxidhfyJYo',
    appId: '1:955866805727:web:e01819055d01f68ae8c06a',
    messagingSenderId: '955866805727',
    projectId: 'gad-2023-early',
    authDomain: 'gad-2023-early.firebaseapp.com',
    storageBucket: 'gad-2023-early.appspot.com',
    measurementId: 'G-E84XKHEBP5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZLKp0kXskaPJA7Gza71RS_jKHQxCF_sA',
    appId: '1:955866805727:android:5d1eaef8ab427bb0e8c06a',
    messagingSenderId: '955866805727',
    projectId: 'gad-2023-early',
    storageBucket: 'gad-2023-early.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDmidk3RKjZqkQrhjxOtVQ5YFCQpcDxemo',
    appId: '1:955866805727:ios:6b0efe2e670b5712e8c06a',
    messagingSenderId: '955866805727',
    projectId: 'gad-2023-early',
    storageBucket: 'gad-2023-early.appspot.com',
    iosClientId:
        '955866805727-2sdmjcg1s8spqiqr1f3jlv59iqcflpfm.apps.googleusercontent.com',
    iosBundleId: 'com.early2023.gad2023Early2',
  );
}
